### ISSUE TITLE
Build break: @fortawesome/free-solid-svg-icons

### ISSUE THREAD

**Issue by Whamo12** [softrams/bulwark#148]
Build is broken with https://github.com/softrams/bulwark/pull/125

**Problem Locations**
@fortawesome/free-solid-svg-icons

**Steps to Reproduce**

1. Check out branch `git fetch && git checkout dependabot/npm_and_yarn/frontend/develop/fortawesome/free-solid-svg-icons-5.14.0`
2. run `npm install`
3. Notice build breaks because of missing icon fa-faHaykal

With @fortawesome/free-solid-svg-icons update, the fa-faHaykal icon has been removed which is breaking the build.  This needs to be reintroduced or replaced with another approved icon.

**Comment by noraj** [comment]
The change was introduced in 5.12.0: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#5112-to-5120

> The 9-pointed icon named "haykal" was renamed to "bahai" to better match the symbol. If you were previously using the misnamed icon rename to "bahai" when upgrading.
