### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by noraj** [softrams/bulwark#245]
**Describe the solution you'd like**

Create a dockerized version of Bulwark for easy & fast deployment with docker-compose.

**Describe alternatives you've considered**

https://docs.docker.com/compose/

**Additional context**

I'm the maintainer of the Rawsec Inventory, I recently added Bulwark to the [Collaboration and Report](https://inventory.raw.pm/tools.html#title-tools-collaboration-report) category. I think the most similar project out there is [pwndoc](https://github.com/pwndoc/pwndoc). They have a [docker-compose](https://github.com/pwndoc/pwndoc/blob/master/docker-compose.yml) that you can use as an example.

**Comment by Whamo12** [comment]
@noraj Thank you for the information.  We have had this on the backburner but it is now a good time to implement this.  

cc @skewled

**Comment by Whamo12** [comment]
> I'm the maintainer of the Rawsec Inventory, I recently added Bulwark to the [Collaboration and Report](https://inventory.raw.pm/tools.html#title-tools-collaboration-report) category.
>

Awesome! Just FYI, it's misspelled in the inventory (remove the extra L).

**Comment by noraj** [comment]
> it's misspelled in the inventory (remove the extra L).

It will be fixed in a few minutes.

**Comment by Whamo12** [comment]
@noraj We added steps for easy deployments with docker-compose.  If you are interested, the steps are located on the README.

https://github.com/softrams/bulwark#launch-with-docker
