### ISSUE TITLE
PrimeNG: Add assessment table tester column filtering

### ISSUE THREAD

**Issue by Whamo12** [softrams/bulwark#319]
Currently, a user can only sort the Tester column of the Assessment table which makes it tedious to search for a specific tester and their assigned assessments.

The solution is to utilize the PrimeNG multiselect component as a way to filter selected Testers with the tester column values.

Multiselect: https://primefaces.org/primeng/showcase/#/multiselect
Table documentation: https://primefaces.org/primeng/showcase/#/table 

Example:
![Screen Shot 2020-10-01 at 4 20 05 PM](https://user-images.githubusercontent.com/1582016/94925553-6537fd00-048d-11eb-9ec6-d0559a24efcd.png)

**Comment by bmayen** [comment]
@Whamo12 I have a fix for this, but I created my own branch instead of forking. Cannot push that branch to create a PR. How should I proceed?

**Comment by Whamo12** [comment]
@bmayen The most efficient plan of action would be to open a pull request from a fork.
