### ISSUE TITLE
PrimeNG: Refactor navbar to use PrimeNG menubar

### ISSUE THREAD

**Issue by Whamo12** [softrams/bulwark#320]
The current nav bar should be refactored to utilize PrimeNG components.  I think the PrimeNG [menubar](https://primefaces.org/primeng/showcase/#/menubar) would be a good place to start but I'm open to other creative ideas.

Furthermore, as part of this issue, please fix the alignment of the loading bar.  Currently, it's off center.  Please see image below:

<img width="2263" alt="Screen Shot 2020-10-02 at 9 18 28 AM" src="https://user-images.githubusercontent.com/1582016/94928615-f610d780-0491-11eb-84b4-46ed19f997b4.png">

**Comment by JoelLau** [comment]
hi @Whamo12, can I take this up as part of hacktoberfest?

**Comment by Whamo12** [comment]
@JoelLau yes, you're welcome to it! Just make sure you following the contribution guidelines.

Just a FYI, the menu dropdown in the navbar should also be updated to use primeng.

Thanks, and good luck.
