### ISSUE TITLE
PrimeNG: Refactor Organization Form Component

### ISSUE THREAD

**Issue by Whamo12** [softrams/bulwark#367]
The Organization form component, used for creating and updating forms, should be refactored to use [PrimeNG](https://www.primefaces.org/primeng/showcase/#/)'s form components so that the styling is consistent with the remainder of the application.

Relative path: `frontend/src/app/org-form`

**Comment by NOPROD** [comment]
Finaly i try this issue. (i finish set up , exploration, etc.. ^^) #378 is really big (240 lines)

**Comment by Whamo12** [comment]
@NOPROD Great work on #384! Thank you for your contribution! If there are any tips/tricks you would like to share, please let us know in a new ticket.
