### ISSUE TITLE
PrimeNG: Refactor Password-Reset component

### ISSUE THREAD

**Issue by Whamo12** [softrams/bulwark#374]
The Password-Reset form component, used for creating and updating forms, should be refactored to use [PrimeNG](https://www.primefaces.org/primeng/showcase/#/)'s form components so that the styling is consistent with the remainder of the application.

Relative path: `frontend/src/app/password-reset`

**Comment by NOPROD** [comment]
On it ^^

**Comment by Whamo12** [comment]
Looks good! Thank you for another contribution!
