### ISSUE TITLE
PrimeNG: Refactor Settings Form Component

### ISSUE THREAD

**Issue by Whamo12** [softrams/bulwark#376]
The Settings form component, used for creating and updating forms, should be refactored to use [PrimeNG](https://www.primefaces.org/primeng/showcase/#/)'s form components so that the styling is consistent with the remainder of the application.

Relative path: `frontend/src/app/settings`

**Comment by NOPROD** [comment]
On it ^^

**Comment by Whamo12** [comment]
Looks good! Thank you for another contribution!
