### ISSUE TITLE
PrimeNG: Refactor Vuln-Form Form Component

### ISSUE THREAD

**Issue by Whamo12** [softrams/bulwark#378]
The Vuln-Form form component, used for creating and updating forms, should be refactored to use [PrimeNG](https://www.primefaces.org/primeng/showcase/#/)'s form components so that the styling is consistent with the remainder of the application.

Relative path: `frontend/src/app/vuln-form`

**Comment by NOPROD** [comment]
@Whamo12  Ok i try

**Comment by Whamo12** [comment]
@NOPROD Just FYI, the `vuln-form.component.ts` is the biggest form in the application.  If you want something a little more simple, check out #367 or #369
