### ISSUE TITLE
docker install: no manifest

### ISSUE THREAD

**Issue by noraj** [softrams/bulwark#434]
**Describe the bug**

When building the docker container I have an error message telling me a manifest file is not existing and crash after that.
The weird part is that I don't even find a reference to the word manifest in the [code](https://github.com/softrams/bulwark/search?q=manifest).

```
Pulling bulwark (softramsdocker/bulwark:6.2.3)...
ERROR: manifest for softramsdocker/bulwark:6.2.3 not found: manifest unknown: manifest unknown
```

**Steps to Reproduce**

```
$ git clone https://github.com/softrams/bulwark.git
$ cd bulwark
$ git checkout v6.2.3
$ nvim .env # create the env file
$ sudo docker-compose up -d
```

**Expected behavior**

Building without issue.

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser : NA
 - Version : Bullwark 6.2.3
- docker-compose version 1.27.4, build unknown
- Docker version 19.03.13-ce, build 4484c46d9

**Comment by Whamo12** [comment]
This is most likely due the image not having the latest tag.  We will take care of this.  Thanks for the heads up, @noraj !

**Comment by skewled** [comment]
Updated to use latest, checking migration script issues.

**Comment by Whamo12** [comment]
@noraj update to the latest 6.2.4 for the fix.  Let us know if there are any other issues.

**Comment by noraj** [comment]
Now the container builds correctly.
