### ISSUE TITLE
docker-compose: Internal server error

### ISSUE THREAD

**Issue by noraj** [softrams/bulwark#443]
**Describe the bug**

I can't connect, CSP seems to block some scripts.

**Problem Locations**

- Pink rectangle : before login
- Red rectangle : after login

![image](https://user-images.githubusercontent.com/16578570/99229442-54014080-27ee-11eb-8e57-1d97964409bf.png)

On docker logs this message is appearing even if I have a `.env` file (idk if it is related at all):

```
bulwark       | A .env file was not found. Attempting to fetch values from existing environment variables.
```

**Steps to Reproduce**

```
$ git clone https://github.com/softrams/bulwark.git
$ cd bulwark
$ git checkout v6.2.4
$ nvim .env # create the env file
$ sudo docker-compose up -d
```

**Expected behavior**

Login without error.

**Desktop (please complete the following information):**

- OS: ArchLinux
- Browser : Firefox 82.0.3, Chromium 86.0.4240.198
- Version : Bullwark 6.2.4
- docker-compose version 1.27.4, build unknown
- Docker version 19.03.13-ce, build 4484c46d9

**Comment by Whamo12** [comment]
The CSP is a known issue we are looking into but it should not have blocked you from logging in.  By chance, have you tried using the .env [template](https://github.com/softrams/bulwark#launch-with-docker) from the README? Are there any server errors showing up in the terminal?

**Comment by noraj** [comment]
> By chance, have you tried using the .env template from the README? 

Yes I used this one.

> Are there any server errors showing up in the terminal?

No none. Each time I try to login no new log output on the docker server side, only the CSP error appearing over and over on client side, for my pov it looks like the CSP is blocking the front app to reach the API `/api/login`.

**Comment by Whamo12** [comment]
Hey @noraj  I noticed you're doing `git checkout v6.2.4`.  Could try using master instead?

**Comment by skewled** [comment]
Tested on both 6.2.4 as well as from master, and unable to replicate the CSP errors noted.
![Screen Shot 2020-11-17 at 11 58 00 AM](https://user-images.githubusercontent.com/64661963/99422735-d7459380-28cd-11eb-89a2-4eaa6eecc2da.png)


Using the specified versions below.
OS: ArchLinux
Browser : Firefox 83.0, Chromium Version 86.0.4240.198 (Official Build) Arch Linux (64-bit)
Version : Bullwark 6.2.4
docker-compose version 1.27.4, build unknown
Docker version 19.03.13-ce, build 4484c46d9

**Comment by skewled** [comment]
Using 'localhost' over the '127.0.0.1' address is working.

**Comment by skewled** [comment]
@noraj can you confirm you can access via http://localhost:5000 ?

**Comment by noraj** [comment]
Confirmed.
