### ISSUE TITLE
Can the programme be predefined with a vulnerability template?

### ISSUE THREAD

**Issue by xiaoliangli1128** [softrams/bulwark#447]
Thank you very much for your program!
Can the program be predefined with a vulnerability template?
When we write a report, we create a vulnerability,The  program  displays the predefined vulnerability templates  and we just need to modify and improve a few details to get the report right!

**Comment by Whamo12** [comment]
@xiaoliangli1128 thanks for reaching out. Vulnerability templates are something we have discussed internally in the past as a goal. We envision a feature where the application contains a list of current known vulnerabilities that a user could pick as a template for their report. In addition to this, provide the user to create custom vulnerabilities. Is this along the lines of what you mentioned?

**Comment by Whamo12** [comment]
@skewled  I received a suggestion from [atticuss](https://github.com/Atticuss) to use CWE.  I just discovered an OWASP node library that could be utilized to fetch the CWE data which could be used as a starting point for the vulnerability templates.

**Comment by skewled** [comment]
@Whamo12 we will discuss internally and determine a few options to move forward with adding the enhancement as well as timing of adding it. 👍

**Comment by xiaoliangli1128** [comment]
@Whamo12  Yes, that's exactly what I want.

**Comment by Whamo12** [comment]
Reopening this issue to track development progress.

**Comment by Whamo12** [comment]
This will be worked on with #481
