### ISSUE TITLE
Implement Vulnerability Templates

### ISSUE THREAD

**Issue by Whamo12** [softrams/bulwark#481]
**Is your feature request related to a problem? Please describe.**
Integrate CWE into Bulwark so that the vulnerability form can auto-populate from information from CWE.

**Describe the solution you'd like**
We can use [fetch-cwe-list](https://www.npmjs.com/package/fetch-cwe-list) for fetching the latest findiings from CWE using a background job or an admin button.

**Additional context**
https://cwe.mitre.org/

**Comment by Whamo12** [comment]
Another idea that could be quick would to have a "Save as Vulnerability Template" button which will store a template in a "vulnerability_template" table that could be later fetched when writing up findings.

**Comment by noraj** [comment]
> Another idea that could be quick would to have a "Save as Vulnerability Template" button which will store a template in a "vulnerability_template" table that could be later fetched when writing up findings. This could be an entirely separate implementation from CWE integration.

Yes it should be an entirely separate implementation from CWE integration. And yes there could be a "Save as Vulnerability Template" button  but the other way around is also needed filling directly a vulnerability template and a "add vulnerability" bustton inside audit/assessment see #785.
