### ISSUE TITLE
Two page report for no vulnerabilites

### ISSUE THREAD

**Issue by waterweasel4** [softrams/bulwark#489]
**Describe the bug**
When a report contains no vulnerabilities, the PDF generated is two pages with the second page being blank.

**Problem Locations**
Generate a report for a no vulnerability finding assessment > download the PDF > notice the PDF has two pages

**Steps to Reproduce**
1. Go to an assessment with no vulnerabilities.
2. Click on Preview Report.
3. Click Generate Report.
4. Download the PDF and notice it has two pages, the second being blank.

**Expected behavior**
The second page, if it has no data, should not be included.

**Screenshots**
<img width="1187" alt="Screen Shot 2020-12-10 at 4 26 16 PM" src="https://user-images.githubusercontent.com/8419327/101831768-6e37f100-3b04-11eb-8ea8-c22e47f9b854.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 87

**Additional context**
N/A

**Comment by Whamo12** [comment]
Yeah, we definitely need to look at this.  We are also having issues with screenshots where it will add blank pages depending on the size of the image.  Makes reports look more bloated than they are.
