### ISSUE TITLE
Create Administration Component

### ISSUE THREAD

**Issue by Whamo12** [softrams/bulwark#491]
**Is your feature request related to a problem? Please describe.**
Currently future administration functionality such as inviting users to Bulwark, company name setting, and email settings are in separate locations.  We need to consolidate these components into a single Administration component.

**Comment by waterweasel4** [comment]
![adminarea](https://user-images.githubusercontent.com/8419327/101988712-65acfb00-3c69-11eb-92f4-9b366f82b60b.png)

Here's a screenshot of the proposed new interface.  Then we can wrap that into the 'administrator' role once that feature is added.

**Comment by Whamo12** [comment]
This look good.  As you said, once the roles implementation feature is finished, we will be able to consolidate all the features here.
