### ISSUE TITLE
Incorrect application's requests.

### ISSUE THREAD

**Issue by lizzmack101** [softrams/bulwark#565]
**Describe the bug**
An application makes requests to the http://localhost:5000/api/login, but:
1) csp blocks it because, i access an app via internal ip, such as 172.17.0.60:5000
2) i don't have bulwark locally, that's why request to http://localhost is useless.

![image](https://user-images.githubusercontent.com/45513932/105883318-c6c14000-6017-11eb-8608-27d24579e7c0.png)

for deploying i use docker-compose 1.28 (latest)
.env file as default.

**Steps to Reproduce**
1. deploy via docker-compose on a remote machine
2. access an application across the web via remote IP
3. try to login

Also i tried to change .env file providing prod url as ip of the remote machine. but it didn't work. issue is similar to number 443? but i DO NOT NEED access the application via "localhost" url locally...

**Comment by Whamo12** [comment]
@lizzmack101 thanks for submitting the bug.  This might be related to https://github.com/helmetjs/helmet/issues/237 as `default-src` is mandatory with Helmet.  We will take a look.

**Comment by lizzmack101** [comment]
thanks for fast csp fix, i'd like to mention, that the problem of incorrect address to request - is present too.
Also, as i see in docker bulwark logs after deployment, is that the last action is like the following, and i suppose, that this could be a problem, because it doesn't see an .env file in root dir of the application: 
![image](https://user-images.githubusercontent.com/45513932/106009300-3ba08280-60c9-11eb-8300-f7daf00d669a.png)

Hope this will help to understand, what i mean.

**Comment by Whamo12** [comment]
> 
> 
> thanks for fast csp fix, i'd like to mention, that the problem of incorrect address to request - is present too.
> Also, as i see in docker bulwark logs after deployment, is that the last action is like the following, and i suppose, that this could be a problem, because it doesn't see an .env file in root dir of the application:
> ![image](https://user-images.githubusercontent.com/45513932/106009300-3ba08280-60c9-11eb-8300-f7daf00d669a.png)
> 
> Hope this will help to understand, what i mean.

@lizzmack101  you are correct and this is a separate issue that we are investigating.  It looks like we are missing two `process.env` variables in our `.env` file instructions.  As you can see in the following [code](https://github.com/softrams/bulwark/blob/master/src/app.ts#L58) we have written:

```
const serverPort = process.env.PORT || 5000;
const serverIpAddress = process.env.IP || '127.0.0.1';
```
If we do not provide the `PORT` and `IP` it'll set default values (localhost).  Could you try adding two additional `process.env` variables to your `.env` to see if it fixes the issue?

```
PORT: "5000"
IP: "172.17.0.60"

**Comment by lizzmack101** [comment]
So, I added to .env IP PORT lines,
IP=172.17.0.60
port=5000

but logs inside a container - still doesn't see .env  file. Nothing changed in this case. See following screen:
![image](https://user-images.githubusercontent.com/45513932/106014426-8a045000-60ce-11eb-89d7-7432fa5a6a0d.png)
![image](https://user-images.githubusercontent.com/45513932/106014586-aa340f00-60ce-11eb-9c95-c9c2b85e0399.png)
![image](https://user-images.githubusercontent.com/45513932/106014661-bd46df00-60ce-11eb-89a7-32934d77beb5.png)

After that, i do cp of .env inside a container "bulwark":
![image](https://user-images.githubusercontent.com/45513932/106014834-ecf5e700-60ce-11eb-8855-d4b4edf47f50.png)
restart containers
![image](https://user-images.githubusercontent.com/45513932/106015078-2af30b00-60cf-11eb-92dc-3c9b3cb84aca.png)
![image](https://user-images.githubusercontent.com/45513932/106015139-39d9bd80-60cf-11eb-8df7-ce628b9796da.png)
but the application still enforces "localhost" url at login request
![image](https://user-images.githubusercontent.com/45513932/106015298-642b7b00-60cf-11eb-853b-2c4fe8be54bd.png)

After this, I go inside the "bulwark" container and edit .env like this:
![image](https://user-images.githubusercontent.com/45513932/106016080-28dd7c00-60d0-11eb-86d0-a90144bc3154.png)



againt restart,

![image](https://user-images.githubusercontent.com/45513932/106016261-54606680-60d0-11eb-8a38-ceff8aa5a0a9.png)


 and still localhost request at login page:
![image](https://user-images.githubusercontent.com/45513932/106016360-722dcb80-60d0-11eb-8344-72816a7bf929.png)

**Comment by Whamo12** [comment]
@lizzmack101 Thank you for your patience.  We've been working behind the scenes to attempt to resolve this issue.  The main cause of this bug was due to the fact that Angular had `http://localhost:5000` hardcoded in the environment files.  We have modified the application scripts to dynamically update Angular's environment with the correct API URL.  This fix has been pushed to the `develop` branch and will be available in a week or two in the main branch.  If you would like to test the fixed code, please checkout the `develop` branch and let us know.  That would be greatly appreciated.

We have updated the README with the latest [changes](https://github.com/softrams/bulwark/blob/develop/README.md#launch-with-docker).    Essentially, we have an additional environment variable for the server address:

```
MYSQL_DATABASE="bulwark"
MYSQL_PASSWORD="bulwark"
MYSQL_ROOT_PASSWORD="bulwark"
MYSQL_USER="root"
MYSQL_DB_CHECK="mysql"
DB_PASSWORD="bulwark"
DB_URL="172.16.16.3"
DB_ROOT="root"
DB_USERNAME="bulwark"
DB_PORT=3306
DB_NAME="bulwark"
DB_TYPE="mysql"
NODE_ENV="production"
DEV_URL="http://localhost:4200"
SERVER_ADDRESS="http://localhost"
PORT=5000
JWT_KEY="changeme"
JWT_REFRESH_KEY="changeme"
CRYPTO_SECRET="changeme"
CRYPTO_SALT="changeme"
```

Additionally, we have created the script `npm run config` to dynamically update Angular environment based on `server_address` and `port`.  Additional information can be found [here](https://github.com/softrams/bulwark/blob/develop/README.md#local-installation).

We look forward to hearing back from you!
