### ISSUE TITLE
Implement Github Action for Testing/Linting

### ISSUE THREAD

**Issue by Whamo12** [softrams/bulwark#6]
As a system, a Github action needs to be created so that pull requests automatically run linting and future unit testing.

A Github action is required to run linting and unit testing on pull requests before merging is possible.  This will avoid breaking the build in the `master` and `develop` environments. 

https://github.com/actions/typescript-action

**Comment by Atticuss** [comment]
@Whamo12 can you drop the commands to run the lint and unit tests?

**Comment by Whamo12** [comment]
`npm run lint` is the script for linting.  Unit tests are still being worked on but eventually it will be `npm run test`.  I would leave that commented out for now until the unit tests are ready.

Furthermore, the `npm install` script will build both the client side and server side code in production mode.

**Comment by Atticuss** [comment]
Dropping some notes for myself for when I start tackling this

https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

https://github-actions.explore-tech.org/npm-cli

https://github.com/marketplace/actions/merge-pull-requests

https://stackoverflow.com/questions/58654530/how-to-reject-a-pull-request-if-tests-are-failed-github-actions

https://help.github.com/en/github/administering-a-repository/enabling-required-status-checks

https://alexwlchan.net/2019/03/creating-a-github-action-to-auto-merge-pull-requests/

**Comment by Whamo12** [comment]
@Atticuss  to add on to your list

Here's a vanilla guide for node js github actions.  We would essentially need three scripts to be ran:

https://help.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions  

1. `npm install`
2. `npm run lint`
3. `npm run test` - commented out initially until we have more tests done.

**Comment by Atticuss** [comment]
Don't think you'll even need an action to achieve this:

https://help.github.com/en/github/administering-a-repository/about-required-status-checks
