### ISSUE TITLE
Implement Backend Unit Testing

### ISSUE THREAD

**Issue by Whamo12** [softrams/bulwark#7]
Currently the back-end code lacks unit testing.  This ticket is responsible for setting up the initial unit testing framework and is required before any unit tests are implemented.

**Comment by DarrellRichards** [comment]
@Whamo12 
You have no idea who I am, but I'll be starting at Softrams on Monday (7/13). I just wanted to put 2 cents in here is all. 

We could run Jasmine across the board here with Karma. If you wish not to, you could use Jest and Enzyme. 

We could go an entirely different path, I have no issue with tackling this issue if allowed.

**Comment by Whamo12** [comment]
@DarrellRichards Welcome to the team! You're more than welcome to contribute as long as you follow the [contribution guidelines](https://github.com/softrams/bulwark/blob/master/CONTRIBUTING.md).  This ticket is just to setup the framework.  We will create additional tickets to start adding tests after.

**Comment by Whamo12** [comment]
@DarrellRichards Thanks for the contribution.  If you're feeling up to it, create an issue with an initial test + necessary documentation so others can follow along.
