### ISSUE TITLE
Implement Syntax Highlighting for Markdown Support

### ISSUE THREAD

**Issue by Whamo12** [softrams/bulwark#767]
**Is your feature request related to a problem? Please describe.**
Syntax highlighting should be available so that the markdown renders source code accurately based on programming language

**Describe the solution you'd like**
https://github.com/jfcere/ngx-markdown#syntax-highlight

**Comment by Whamo12** [comment]
Thanks, @noraj! I'll check out the resource you linked.  The main concern I have with ngx-markdown is that you manually have to import the syntax highlighting per language.  Therefore, we would have to import only the more popular languages with README instructions showing how to add languages other than the defaults we provided.  Or we do not provide syntax highlighting out of the box and instead have instructions on how to enable it by updating the angular.json.

> But about Syntax Highlighting it's nice to have it client-side but what about Syntax Highlighting during report generation? Because being able to get it in the final report (PDF) is as important if not more.

I tested this out using Prism.js and confirmed that Puppeteer renders the report with partial syntax highlighting.  Albeit, with a light background instead of a dark background.  Here's a Java example:

![Image from iOS](https://user-images.githubusercontent.com/1582016/117848283-281cc000-b251-11eb-805b-367c2382ab0a.jpg)

**Comment by noraj** [comment]
> The main concern I have with ngx-markdown is that you manually have to import the syntax highlighting per language. Therefore, we would have to import only the more popular languages with README instructions showing how to add languages other than the defaults we provided. Or we do not provide syntax highlighting out of the box and instead have instructions on how to enable it by updating the angular.json.

I know that with  Highlight.js you have only one script to embed, you can include all languages, include only common ones or include a custom list cf. https://highlightjs.org/download/ and https://highlightjs.org/usage/.
I don't know Pirsm.js well. The only usage I've seen is in Docsify and it was teh same you were forced to import one module per language.
