### ISSUE TITLE
Vulnerability database/library

### ISSUE THREAD

**Issue by noraj** [softrams/bulwark#785]
Bulwark is lacking of the most important feature of them all: having a vulnerability database.

Dradis, Ghostwriter, PwnDoc, WriteHat, etc. all collaborative penetration test reporting platforms have that, sometimes under a different name like _issue library_ etc.

The idea is that you can save _generic_ vulnerabilities since description and recommendation will always be the same or will require very few changes, you link the same resources, have the same title etc. So when you do a new pentest you can import a vulnerability in your audit an just have to change very few things and add your observations, details and proof in the field you name _Detailed Information_ and re-use most of the rest. And so saving a lot of time.

The best vulnerability database implementation I have seen if from [pwndoc](https://github.com/pwndoc/pwndoc) if you want to quickly deploy their docker and see what I mean.

**Comment by noraj** [comment]
You can browse your vulnerability DB alone

![image](https://user-images.githubusercontent.com/16578570/117956750-a2b11280-b319-11eb-9020-0f409d9d5832.png)

Or add a vuln from your vuln DB into an audit

![image](https://user-images.githubusercontent.com/16578570/117957011-e7d54480-b319-11eb-8dd3-72f5d9c11a56.png)

**Comment by Whamo12** [comment]
Note: Relates to #481

**Comment by noraj** [comment]
> Note: Relates to #481

I'll comment there

**Comment by Whamo12** [comment]
After reviewing, this should not be too difficult as it would use the same Angular component for the current vulnerability form.  The question would be how we would store this in the database.  Initial thoughts would be that we could create a new table called `Vulnerability_Template` which would be almost an exact replica of the `Vulnerability` table without the assessment relation.  The only relations it would have would be for `resources`.  Relations for `problemLocations`, and `resources` would be specific for the vulnerability being written up and should be empty in the vuln DB.  Finally, when we create an actual vulnerability against an assessment, we could have the vuln DB be a dropdown pick-list which would populate the form automatically.

Example:

```
@Entity()
export class Vulnerability {
  @PrimaryGeneratedColumn()
  id: number;
  @Column()
  jiraId: string;
  @Column()
  @IsIn(['Low', 'Medium', 'High'])
  impact: string;
  @Column()
  @IsIn(['Low', 'Medium', 'High'])
  likelihood: string;
  @Column()
  @IsIn(['Low', 'Medium', 'High', 'Critical', 'Informational'])
  risk: string;
  @Column()
  @IsIn(['Yes', 'No'])
  systemic: string;
  @Column({ type: 'decimal', scale: 1, precision: 10 })
  @IsDecimal()
  cvssScore: number;
  @Column()
  @IsUrl()
  cvssUrl: string;
  @Column()
  @IsIn(['Open', 'Resolved', 'On Hold'])
  status: string;
  @Column({ length: 4000 })
  @MaxLength(4000)
  description: string;
  @Column({ length: 4000 })
  @MaxLength(4000)
  detailedInfo: string;
  @Column({ length: 4000 })
  @MaxLength(4000)
  remediation: string;
  @Column()
  name: string;
  @OneToMany((type) => File, (file) => file.vulnerability)
  screenshots: File[];
  @OneToMany((type) => ProblemLocation, (problemLocation) => problemLocation.vulnerability)
  problemLocations: ProblemLocation[];
  @OneToMany((type) => Resource, (resource) => resource.vulnerability)
  resources: Resource[];
}
```

**Comment by noraj** [comment]
I don't known what is the right DB architecture.

Here what's down in PwnDoc (they use mongoDB):

- https://github.com/pwndoc/pwndoc/blob/master/backend/src/routes/vulnerability.js
- https://github.com/pwndoc/pwndoc/blob/master/backend/src/models/vulnerability.js
- https://github.com/pwndoc/pwndoc/blob/master/backend/src/models/vulnerability-update.js
- https://github.com/pwndoc/pwndoc/blob/master/backend/src/models/vulnerability-type.js
- https://github.com/pwndoc/pwndoc/blob/master/backend/src/models/vulnerability-category.js

> we could have the vuln DB be a dropdown pick-list which would populate the form automatically.

I don't think this is the way to go. This way you can't add several vulns at a time to your audit/assessment. Also a drowpdown list doesn't allow to search and is a nightmare once you get hundreds of vulns.

**Comment by noraj** [comment]
Is it really closed as completed? Or as wontfix?
